<template><div>
    <h2>Trading Platform Notice: Use of Breeze API</h2>
    <p>We would like to inform you that our trading operations are now conducted using the Breeze API. This advanced API allows for seamless and secure execution of trades, providing enhanced efficiency and reliability in our trading processes.</p>
    <h3>Key Benefits of Breeze API:</h3>
    <ol>
        <li>Robust Security: Breeze API employs industry-leading security measures to safeguard your trading activities, ensuring the confidentiality and integrity of your transactions.</li>
        <li>Scalability: With Breeze API, our trading platform is equipped to handle increased trading volumes and complexities, enabling us to meet the evolving needs of our users.</li>
        <li>Ease of Integration: Integrating Breeze API into our trading platform streamlines the trading experience, offering users a user-friendly interface and seamless access to trading functionalities.</li>
    </ol>
    <p>You can create an app to get API key and Secret at -> <a href="https://api.icicidirect.com/apiuser/home" target="_blank">ICICI Direct App generation</a> and in redirect link put - <strong>//#/#/authsuccess</strong></p>
    <p><strong>Important Note:</strong> In order to continue trading on our platform, users are required to provide their unique API key and API secret generated by Breeze API. These credentials will ensure secure authentication and authorization for accessing our trading services.</p>
    <div class="api-credentials">
        <p><strong>API Key:</strong> 
        
            <vsud-input v-model="api_key" id="api_key" type="text" placeholder="api_key" name="api_key" required/>
        </p>
        <p><strong>API Secret:</strong> 
        
            <vsud-input v-model="api_secret" id="api_secret" type="password" placeholder="api_secret" name="api_secret" required/>
        </p>
        <div class="text-center">
                      <vsud-button
                        class="my-4 mb-2"
                        variant="gradient"
                        color="info"
                        full-width
                        v-on:click.prevent="sendapidata"
                      >Submit</vsud-button>
                      <vsud-button
                        class="my-4 mb-2"
                        variant="gradient"
                        color="primary"
                        full-width
                        v-on:click.prevent="refreshpage"
                      >Cancel</vsud-button>
        
                    </div>
    </div>

    <p>If you have any questions or concerns regarding the transition to Breeze API or need assistance with generating your API credentials, please don't hesitate to reach out to our customer support team.</p>
    <p>Thank you for your continued trust and support as we strive to enhance your trading experience through innovative solutions like Breeze API.</p>
  </div>
</template>

<script>

import VsudInput from "@/components/VsudInput.vue";
import VsudSwitch from "@/components/VsudSwitch.vue";
import VsudButton from "@/components/VsudButton.vue";
import {axiosClientIns} from "@/libs/client_axios";
import Cookies from "js-cookie";

export default{
    name: "Setup",
  props: ['modelValue'],
  emits: ['update:modelValue'],
  components: {
    VsudInput,
    VsudSwitch,
    VsudButton,
  },
  data: () => ({
    uid: Cookies.get('uid', {domain: import.meta.env.VITE_APP_Parent_Domain}),
    vite_username: Cookies.get('vite_username', {domain: import.meta.env.VITE_APP_Parent_Domain}),
    api_key: '',
    api_secret: '',
    }
    
  ),
  methods:{
    refreshpage(){
      location.reload();
    },
    sendapidata: async function () {
        axiosClientIns
        .post("/save_tradekeys",{
            'filter': {"user":Cookies.get('vite_username')},
            'fields': {'api_key':api_key, 'api_secret':api_secret},
            'username': this.vite_username,
            'uid': this.uid
            }).then(response =>{
                if (response.data.status){  
                  console.log('refresh')
                  window.location.reload();
                }
            })


    },
  }
}
</script>
